from django.urls import path

from .views import (
    FavoriteListView,
    HealthView,
    HouseDetailView,
    HouseListCreateView,
    RegisterView,
    ReservationListCreateView,
    ReviewListCreateView,
    VisitRequestListCreateView,
    admin_dashboard,
    admin_publication_invoice_list,
    admin_publication_invoice_mark_under_review,
    admin_publication_invoice_review,
    admin_user_delete,
    admin_user_detail,
    admin_user_toggle_certified,
    admin_user_update,
    admin_update_settings,
    admin_validate_house,
    cancel_visit,
    cancel_reservation,
    create_or_get_publication_invoice,
    delete_favorite,
    delete_reservation,
    delete_visit,
    download_publication_invoice_pdf,
    login_view,
    logout_view,
    me_view,
    owner_dashboard,
    owner_stop_house_publication,
    owner_publication_invoice_detail,
    owner_publication_invoices,
    owner_reservation_action,
    owner_visit_action,
    pay_visit_deposit,
    submit_publication_invoice_proof,
    toggle_favorite,
)

urlpatterns = [
    path("health/", HealthView.as_view(), name="health"),
    path("auth/register/", RegisterView.as_view(), name="register"),
    path("auth/login/", login_view, name="login"),
    path("auth/logout/", logout_view, name="logout"),
    path("auth/me/", me_view, name="me"),
    path("houses/", HouseListCreateView.as_view(), name="house-list"),
    path("houses/<int:pk>/", HouseDetailView.as_view(), name="house-detail"),
    path("houses/<int:house_id>/reviews/", ReviewListCreateView.as_view(), name="house-reviews"),
    path("houses/<int:house_id>/favorite/", toggle_favorite, name="toggle-favorite"),
    path("houses/<int:house_id>/validate/", admin_validate_house, name="admin-house-validate"),
    path("houses/<int:house_id>/publication-invoice/", create_or_get_publication_invoice, name="publication-invoice-create-or-get"),
    path("owner/houses/<int:house_id>/stop-publication/", owner_stop_house_publication, name="owner-house-stop-publication"),
    path("favorites/", FavoriteListView.as_view(), name="favorites"),
    path("favorites/<int:favorite_id>/", delete_favorite, name="favorite-delete"),
    path("visits/", VisitRequestListCreateView.as_view(), name="visits"),
    path("visits/<int:visit_id>/", delete_visit, name="visit-delete"),
    path("visits/<int:visit_id>/cancel/", cancel_visit, name="visit-cancel"),
    path("visits/<int:visit_id>/pay-deposit/", pay_visit_deposit, name="pay-visit-deposit"),
    path("visits/<int:visit_id>/owner-action/", owner_visit_action, name="owner-visit-action"),
    path("reservations/", ReservationListCreateView.as_view(), name="reservations"),
    path("reservations/<int:reservation_id>/", delete_reservation, name="reservation-delete"),
    path("reservations/<int:reservation_id>/cancel/", cancel_reservation, name="reservation-cancel"),
    path("reservations/<int:reservation_id>/owner-action/", owner_reservation_action, name="owner-reservation-action"),
    path("owner/dashboard/", owner_dashboard, name="owner-dashboard"),
    path("owner/publication-invoices/", owner_publication_invoices, name="owner-publication-invoices"),
    path("owner/publication-invoices/<int:invoice_id>/", owner_publication_invoice_detail, name="owner-publication-invoice-detail"),
    path("owner/publication-invoices/<int:invoice_id>/submit-proof/", submit_publication_invoice_proof, name="owner-publication-invoice-submit-proof"),
    path("owner/publication-invoices/<int:invoice_id>/pdf/", download_publication_invoice_pdf, name="owner-publication-invoice-pdf"),
    path("admin/dashboard/", admin_dashboard, name="admin-dashboard"),
    path("admin/settings/", admin_update_settings, name="admin-settings"),
    path("admin/users/<int:user_id>/", admin_user_detail, name="admin-user-detail"),
    path("admin/users/<int:user_id>/update/", admin_user_update, name="admin-user-update"),
    path("admin/users/<int:user_id>/toggle-certified/", admin_user_toggle_certified, name="admin-user-toggle-certified"),
    path("admin/users/<int:user_id>/delete/", admin_user_delete, name="admin-user-delete"),
    path("admin/publication-invoices/", admin_publication_invoice_list, name="admin-publication-invoice-list"),
    path("admin/publication-invoices/<int:invoice_id>/under-review/", admin_publication_invoice_mark_under_review, name="admin-publication-invoice-under-review"),
    path("admin/publication-invoices/<int:invoice_id>/review/", admin_publication_invoice_review, name="admin-publication-invoice-review"),
]
