# Generated by Django 5.1.7 on 2026-04-01 08:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_fee', models.PositiveIntegerField(default=10000)),
                ('reservation_commission_percent', models.PositiveIntegerField(default=10)),
                ('visit_deposit', models.PositiveIntegerField(default=50000)),
                ('featured_fee', models.PositiveIntegerField(default=25000)),
                ('support_fee', models.PositiveIntegerField(default=5000)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=120)),
                ('quartier', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('surface', models.PositiveIntegerField()),
                ('room_surfaces', models.JSONField(blank=True, default=list)),
                ('image_keys', models.JSONField(default=list)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('furnished', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=True)),
                ('electricity', models.BooleanField(default=True)),
                ('available', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('urgent', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('equipments', models.JSONField(default=list)),
                ('publication_paid', models.BooleanField(default=False)),
                ('publication_stopped', models.BooleanField(default=False)),
                ('publication_stopped_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Validée'), ('rejected', 'Refusée')], default='pending', max_length=12)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PublicationPaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=32, unique=True)),
                ('payment_reference', models.CharField(max_length=32, unique=True)),
                ('payment_type', models.CharField(choices=[('publication_fee', 'Frais de publication')], default='publication_fee', max_length=24)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='Ar', max_length=8)),
                ('payment_method', models.CharField(choices=[('orange_money', 'Orange Money')], default='orange_money', max_length=24)),
                ('orange_money_number', models.CharField(default='0372543764', max_length=32)),
                ('orange_money_account_name', models.CharField(default='Tina', max_length=120)),
                ('external_transaction_reference', models.CharField(blank=True, max_length=120)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='publication-payment-proofs/')),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Paiement en attente'), ('PROOF_SUBMITTED', 'Preuve soumise'), ('UNDER_REVIEW', 'En vérification'), ('PAID', 'Payée'), ('REJECTED', 'Refusée'), ('CANCELLED', 'Annulée')], default='PENDING_PAYMENT', max_length=24)),
                ('admin_comment', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication_invoice', to='listings.house')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_invoices', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_publication_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('commission', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'en attente'), ('confirmed', 'confirmée'), ('canceled', 'annulée'), ('completed', 'terminée')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='listings.house')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Client'), ('owner', 'Propriétaire'), ('admin', 'Administrateur')], default='client', max_length=12)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('photo_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'en attente'), ('accepted', 'acceptée'), ('refused', 'refusée'), ('canceled', 'annulée'), ('done', 'visite effectuée'), ('no_show', 'visite non effectuée'), ('converted', 'transformée en réservation')], default='pending', max_length=16)),
                ('deposit_status', models.CharField(choices=[('unpaid', 'non payée'), ('paid', 'payée'), ('refunded', 'remboursée'), ('deducted', 'déduite'), ('kept', 'conservée')], default='unpaid', max_length=16)),
                ('deposit_amount', models.PositiveIntegerField(default=50000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='listings.house')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='listings.house')),
            ],
            options={
                'unique_together': {('user', 'house')},
            },
        ),
    ]
