# Generated by Django 5.1.7 on 2026-04-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_house_contact_fields'),
        ('listings', '0005_userprofile_contact_fields'),
    ]

    operations = [
    ]
