# Generated by Django 5.1.7 on 2026-04-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_house_caution_daily_price'),
        ('listings', '0006_merge_20260401_1410'),
    ]

    operations = [
    ]
